FROM node:20-alpine AS build

WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:1.27-alpine
COPY --from=build /app/dist /usr/share/nginx/html
# nginx.conf é montado pelo docker-compose.prod.yml
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
